### ISSUE TITLE
Infection blocked ( at avast )

### ISSUE THREAD

**Issue by 9renpoto** [takuyaa/kuromoji.js#19]
Help me.
Install blocked by Avast, because `Infection blocked` .

https://raw.githubusercontent.com/takuyaa/kuromoji.js/master/README.md

<img width="859" alt="screen shot 2017-08-02 at 22 44 00" src="https://user-images.githubusercontent.com/520693/28876489-56d4d48e-77d4-11e7-8099-6f281e2cdf6e.png">

**Comment by mocobeta** [comment]
I think you have no choice but to turn off avast as the message suggest... or you could add the domain to exception site list?

**Comment by takuyaa** [comment]
@9renpoto This problem seems to be a false positive of your web filter. Could you update your virus definition or Avast itself and try it again?
If you get same error from Avast, re-open this issue please.
Thanks.
