### ISSUE TITLE
「見れる」の解析結果がおかしい

### ISSUE THREAD

**Issue by yassh** [takuyaa/kuromoji.js#28]
「居れる」はこうなる。

|表層形|品詞|品詞細分類1|品詞細分類2|品詞細分類3|活用型|活用形|基本形|読み|発音|
|---|---|---|---|---|---|---|---|---|---|
|居|動詞|自立|*|*|一段|未然形|居る|イ|イ|
|れる|動詞|接尾|*|*|一段|基本形|れる|レル|レル|

「着れる」はこうなる。

|表層形|品詞|品詞細分類1|品詞細分類2|品詞細分類3|活用型|活用形|基本形|読み|発音|
|---|---|---|---|---|---|---|---|---|---|
|着|動詞|自立|*|*|一段|未然形|着る|キ|キ|
|れる|動詞|接尾|*|*|一段|基本形|れる|レル|レル|

ということは、「見れる」はこうなることが期待される。

|表層形|品詞|品詞細分類1|品詞細分類2|品詞細分類3|活用型|活用形|基本形|読み|発音|
|---|---|---|---|---|---|---|---|---|---|
|見|動詞|自立|*|*|一段|未然形|見る|ミ|ミ|
|れる|動詞|接尾|*|*|一段|基本形|れる|レル|レル|

しかし、実際はこうなる。

|表層形|品詞|品詞細分類1|品詞細分類2|品詞細分類3|活用型|活用形|基本形|読み|発音|
|---|---|---|---|---|---|---|---|---|---|
|見れる|動詞|自立|*|*|一段|基本形|見れる|ミレル|ミレル|

**Comment by takuyaa** [comment]
@yassh こちらは、辞書である mecab-ipadic の仕様になります。

「見」「れる」「見れる」という形態素がそれぞれ辞書に登録されており、「見れる」という1形態素のパスが最もコストが低いため、そのような解析結果となります。いまのところ、 mecab-ipadic のコスト調整などを kuromoji.js として対応することは予定していません。

もしその解析結果で都合が悪いのであれば、参考までにどのような用途でお使いになられているのか教えていただけますか？

**Comment by takuyaa** [comment]
辞書の意図通りの挙動であり、個別の対応予定もないので閉じます。
