### ISSUE TITLE
npmjs.orgのドキュメントが古い (Outdated and misleading description in npmjs.org)

### ISSUE THREAD

**Issue by shokai** [takuyaa/kuromoji.js#3]
すばらしいライブラリありがとうございます。おかげでhubotに一瞬で形態素解析機能を追加できました。

一点だけ、README.mdは問題ないのですが、
https://www.npmjs.com/package/kuromoji#node-js
の、build関数のコールバックが`function(err, tokenizer)`ではなく`function(tokenizer)`になっています。

更新しておいたほうが良いと思います

**Comment by takuyaa** [comment]
Thank you for your report and using kuromoji.js!
I already released 0.0.3 and published it, so now you can see correct description in the npm site.
https://www.npmjs.com/package/kuromoji
