### ISSUE TITLE
can't resolve path .

### ISSUE THREAD

**Issue by DhansAL** [takuyaa/kuromoji.js#46]
Module not found: Error: Can't resolve 'path' in \node_modules\kuromoji\src\loader. I'm using react webpack and nodeJs

**Comment by larvata** [comment]
The main entry in the package.json is for nodejs.
To use the browser version you should add the following config to your webpack.config

```javascript
  resolve: {
    alias: {
      kuromoji$: 'kuromoji/build/kuromoji.js',
    },
  },
```
