### ISSUE TITLE
Any plans for UniDic support?

### ISSUE THREAD

**Issue by fasiha** [takuyaa/kuromoji.js#9]
UniDic is, like IPADIC, a morpheme lexicon which Java Kuromoji has excellent support for. (Well, Atilika says Kuromoji UniDic support is "experimental" but in our experiments it works really well.) Any plans for UniDic support in kuromoji.js? Thanks 🍻!

**Comment by takuyaa** [comment]
In short, I would like to support some other dictionaries, including UniDic. Now I am thinking about the design to do well. It will be late, maybe next year.

**Comment by miikaeru** [comment]
Hi @takuyaa, do you still plan to add support for UniDic?
